# db/config.yml 

# This is a generated File. Do not directly alter this file and expect any changes.
# Modify db/config.kdl instead. 

default: 
  adapter: sqlite3
  database: db/camping.db
  host: localhost
  pool: 5
  timeout: 5000

development: 
  adapter: sqlite3
  database: db/camping.db
  host: localhost
  pool: 5
  timeout: 5000

production: 
  adapter: postgres
  database: kow
  host: localhost
  pool: 5
  timeout: 5000
